#!/bin/sh

extract () {
case $1 in
    *.tar.bz2) tar xjf $1 ;;
    *.tar.gz) tar xzf $1 ;;
    *.bz2) bunzip2 $1 ;;
    *.rar) rar x $1 ;;
    *.gz) gunzip $1 ;;
    *.tar) tar xf $1 ;;
    *.tbz2) tar xjf $1 ;;
    *.tgz) tar xzf $1 ;;
    *.zip) unzip $1 ;;
    *.z) uncompress $1 ;;
    *.c)  ;;
    *.cpp)  ;;
    *.java)  ;;
    *) echo "'$1' cannot be extracted via extract ()" ;;
esac
}

case "$1" in
    --compile)
        extract "$2"
        export filename="$2"
        make || exit 1
        tar pczf "$3" *
    ;;
    --prepare)
        ;;
    --execute)
        export filename="$2"
        tar zxf "$3"
        make -s run
    ;;
esac